### ISSUE TITLE
Cannot read from store within a lambda function

### ISSUE THREAD

**Issue by Krasavchik** [SteinHQ/JS-Client#1]
Hi guys,

I have player with Stein lately, it's really cool.
I have built a small project with Gatsby and used Stein+spreadsheet as the database.
It's working well when I used it on the front end, from the react app. I now want to include the call from a lambda function to make the app secure, but it seems I really can't read from a store inside my lambda function. I really do not understand why. Here is the code and the errors I get:

```
// lambda function js
import SteinStore from "stein-js-client"

const store = new SteinStore(
    "https://api.steinhq.com/v1/storages/PRIVATE"
);

export function handler(event, context, callback) {
    console.log("queryStringParameters", event.queryStringParameters)
    console.log(store);
    store.read("questions").then(result => {
        console.log("result:");
        console.log(result);
    })
}
```

Here is the log from the console:

```
Request from ::ffff:127.0.0.1: GET /questionList
queryStringParameters [Object: null prototype] {}
u {
  url:
   'https://api.steinhq.com/v1/storages/PRIVATE/' }
(node:4144) UnhandledPromiseRejectionWarning: TypeError: r(...) is not a function
    at e.exports.global.fetch (/Users/matt/Documents/htdocs/gatsbydynamic/lambda/questionList.js:1:1625)
    at Promise (/Users/matt/Documents/htdocs/gatsbydynamic/lambda/questionList.js:1:21063)
    at new Promise (<anonymous>)
    at e.exports (/Users/matt/Documents/htdocs/gatsbydynamic/lambda/questionList.js:1:21043)
    at u.read (/Users/matt/Documents/htdocs/gatsbydynamic/lambda/questionList.js:1:20213)
    at Object.s [as handler] (/Users/matt/Documents/htdocs/gatsbydynamic/lambda/questionList.js:1:22728)
    at /Users/matt/Documents/htdocs/gatsbydynamic/node_modules/netlify-lambda/lib/serve.js:143:27
    at Layer.handle [as handle_request] (/Users/matt/Documents/htdocs/gatsbydynamic/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/matt/Documents/htdocs/gatsbydynamic/node_modules/express/lib/router/route.js:137:13)
    at next (/Users/matt/Documents/htdocs/gatsbydynamic/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/matt/Documents/htdocs/gatsbydynamic/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/matt/Documents/htdocs/gatsbydynamic/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/matt/Documents/htdocs/gatsbydynamic/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/matt/Documents/htdocs/gatsbydynamic/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/matt/Documents/htdocs/gatsbydynamic/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/Users/matt/Documents/htdocs/gatsbydynamic/node_modules/express/lib/router/route.js:112:3)
(node:4144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
```

Any clue ?

**Comment by shivensinha4** [comment]
Webpack messes up `require`s in modules. We should set it to exclude stein-js-client.

To do this, create a webpack config file (something like _webpack.functions.js_) if not already, and add this to it:
```javascript
module.exports = {
  externals: {
    "stein-js-client" : {commonjs: "stein-js-client"}
  }
}
```

Then, to serve your source, run:
```
netlify-lambda serve .\source\ -c .\webpack.functions.js
```

Let me know if it works!

**Comment by Krasavchik** [comment]
Great, it is working locally now.
So you know, since I am using Gatsby, I had to change the package.json file like this (to serve the lambda functions which are located in src/lambda in my app):

```
"scripts": {
     ...
    "start:lambda": "netlify-lambda serve --config ./webpack.functions.js src/lambda",
    ...
  }
```

I have yet to try it in production but I definitely let you know.
Thanks ;-)

**Comment by shivensinha4** [comment]
I'm closing this for now. If there's an issue during production, feel free to open this issue again.

**Comment by Krasavchik** [comment]
For production I had to add this to package.json

```
"scripts": {
     ...
    "build:lambda": "netlify-lambda --config ./webpack.functions.js build src/lambda",
    ...
  }
```
